import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  
}>) {
  return (
    <html
      lang="en"
  className="h-full antialiased" 
    >
  <body className="min-h-full flex flex-col bg-[url('/images/zamu-logo-header.jpg')] bg-cover bg-center bg-fixed bg-no-repeat">
  <Navbar />
  {children}
</body>
    </html>
  );
}
